"""Add backtesting, scoring, alerts, and portfolio tables

Revision ID: d9c86ccd5496
Revises: 19b2e0c29f39
Create Date: 2025-11-11 18:02:02.482358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c86ccd5496'
down_revision: Union[str, Sequence[str], None] = '19b2e0c29f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_abs_move_1d', sa.Float(), nullable=True),
    sa.Column('avg_abs_move_5d', sa.Float(), nullable=True),
    sa.Column('avg_abs_move_20d', sa.Float(), nullable=True),
    sa.Column('mean_move_1d', sa.Float(), nullable=True),
    sa.Column('mean_move_5d', sa.Float(), nullable=True),
    sa.Column('mean_move_20d', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'event_type', name='uq_event_stats_ticker_event_type')
    )
    op.create_index(op.f('ix_event_stats_id'), 'event_stats', ['id'], unique=False)
    op.create_index('ix_event_stats_ticker', 'event_stats', ['ticker'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_history_ticker_date')
    )
    op.create_index('ix_price_history_date', 'price_history', ['date'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index('ix_price_history_ticker', 'price_history', ['ticker'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('tickers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('event_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_active', 'alerts', ['active'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_user_id', 'alerts', ['user_id'], unique=False)
    op.create_table('event_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('context_score', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_event_scores_event_id', 'event_scores', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_scores_id'), 'event_scores', ['id'], unique=False)
    op.create_table('user_portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portfolios_id'), 'user_portfolios', ['id'], unique=False)
    op.create_index('ix_user_portfolios_user_id', 'user_portfolios', ['user_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_logs_alert_id', 'alert_logs', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    op.create_index('ix_alert_logs_sent_at', 'alert_logs', ['sent_at'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['user_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_portfolio_positions_portfolio_ticker')
    )
    op.create_index(op.f('ix_portfolio_positions_id'), 'portfolio_positions', ['id'], unique=False)
    op.create_index('ix_portfolio_positions_portfolio_id', 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_positions_ticker', 'portfolio_positions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_positions_ticker', table_name='portfolio_positions')
    op.drop_index('ix_portfolio_positions_portfolio_id', table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_alert_logs_sent_at', table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_index('ix_alert_logs_alert_id', table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index('ix_user_portfolios_user_id', table_name='user_portfolios')
    op.drop_index(op.f('ix_user_portfolios_id'), table_name='user_portfolios')
    op.drop_table('user_portfolios')
    op.drop_index(op.f('ix_event_scores_id'), table_name='event_scores')
    op.drop_index('ix_event_scores_event_id', table_name='event_scores')
    op.drop_table('event_scores')
    op.drop_index('ix_alerts_user_id', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('ix_alerts_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_price_history_ticker', table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index('ix_price_history_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_event_stats_ticker', table_name='event_stats')
    op.drop_index(op.f('ix_event_stats_id'), table_name='event_stats')
    op.drop_table('event_stats')
    # ### end Alembic commands ###
